AUTHORIZED_KEYS = {
    "preprocessing":
        [
            "scans",
            "save_dir",
            "data_dir",
            "specfile_name",
            "sample_name",
            "template_imagefile",
            "comment",
            "beamline",
            "actuators",
            "is_series",
            "rocking_angle",
            "backend",
            "debug",
            "flag_interact",
            "colormap",
            "background_plot",
            "custom_scan",
            "custom_images",
            "custom_monitor",
            "detector",
            "custom_pixelsize",
            "phasing_binning",
            "linearity_func",
            "center_roi_x",
            "center_roi_y",
            "roi_detector",
            "root_folder",
            "beam_direction",
            "sample_offsets",
            "sdd",
            "energy",
            "custom_motors",
            "bragg_peak",
            "direct_beam",
            "dirbeam_detector_angles",
            "outofplane_angle",
            "inplane_angle",
            "centering_method",
            "fix_size",
            "center_fft",
            "pad_size",
            "align_q",
            "ref_axis_q",
            "mask_zero_event",
            "median_filter",
            "median_filter_order",
            "reload_previous",
            "reload_orthogonal",
            "preprocessing_binning",
            "save_rawdata",
            "save_to_npz",
            "save_to_mat",
            "save_to_vti",
            "save_as_int",
            "normalize_flux",
            "photon_threshold",
            "photon_filter",
            "bin_during_loading",
            "frames_pattern",
            "background_file",
            "hotpixels_file",
            "flatfield_file",
            "use_rawdata",
            "interpolation_method",
            "fill_value_mask"
        ],
        "postprocessing": [
            "root_folder",
            "detector",
            "scan",
            "save_dir",
            "data_dir",
            "specfile_name",
            "sample_name",
            "template_imagefile",
            "comment",
            "beamline",
            "actuators",
            "is_series",
            "rocking_angle",
            "backend",
            "debug",
            "flag_interact",
            "colormap",
            "background_plot",
            "custom_scan",
            "custom_images",
            "custom_monitor",
            "detector",
            "custom_pixelsize",
            "phasing_binning",
            "linearity_func",
            "center_roi_x",
            "center_roi_y",
            "roi_detector",
            "beam_direction",
            "sample_offsets",
            "sdd",
            "energy",
            "custom_motors",
            "bragg_peak",
            "direct_beam",
            "dirbeam_detector_angles",
            "outofplane_angle",
            "inplane_angle",
            "reconstruction_file",
            "isosurface_strain",
            "output_size",
            "save_frame",
            "data_frame",
            "simulation",
            "sort_method",
            "averaging_space",
            "correlation_threshold",
            "roll_modes",
            "centering_method",
            "ref_axis_q",
            "strain_method",
            "invert_phase",
            "flip_reconstruction",
            "phase_ramp_removal",
            "threshold_gradient",
            "phase_offset",
            "phase_offset_origin",
            "offset_method",
            "align_axis",
            "ref_axis",
            "axis_to_align",
            "strain_range",
            "phase_range",
            "grey_background",
            "tick_spacing",
            "tick_direction",
            "tick_length",
            "tick_width",
            "get_temperature",
            "reflection",
            "reference_spacing",
            "reference_temperature",
            "half_width_avg_phase",
            "apodize",
            "apodization_window",
            "apodization_mu",
            "apodization_sigma",
            "apodization_alpha",
            "save_rawdata",
            "save_support",
            "save"
        ],
        "pynx": [
            "data",
            "mask",
            "data2cxi",
            "auto_center_resize",
            "support_size",
            "support",
            "support_threshold",
            "support_threshold_method",
            "support_only_shrink",
            "support_update_period",
            "support_smooth_width_begin",
            "support_smooth_width_end",
            "support_post_expand",
            "psf",
            "nb_raar",
            "nb_hio",
            "nb_er",
            "nb_ml",
            "nb_run",
            "nb_run_keep",
            "zero_mask",
            "crop_output",
            "positivity",
            "beta",
            "detwin",
            "rebin",
            "detector_distance",
            "pixel_size_detector",
            "wavelength",
            "verbose",
            "output_format",
            "live_plot",
            "save_plot",
            "mpi"
        ]
}

# AUTHORIZED_KEYS = {
#     'preprocessing': [
#         'beamline',
#         'binning',
#         'rocking-angle',
#         'root_folder',
#         'debug',
#         'detector',
#         'filter',
#         'interact',
#         'mask',
#         'orthogonalize',
#         'output_dir',
#         'sample_name',
#         'save_dir',
#         'sample_detector_distance',
#         'scan',
#         'specfile_name',
#         # 'template-data-file'
#     ],
#     'postprocessing': [
#         'align_q',
#         'angle_step',
#         'center_fft'
#         'centering_method',
#         'background_file',
#         'beamline',
#         'bin_during_loading',
#         'data-root-folderscan',
#         'debug',
#         'energy',
#         'fix_size',
#         'flatfield_file',
#         'flip',   
#         'frames_pattern',
#         'hotpixels_file',
#         'incidence-angle',
#         'inplane-angle',
#         'is-orthogonalized',
#         'isosurface-threshold',
#         'modes',
#         'mask_zero_event',
#         'median_filter',
#         'median_filter_order',
#         'normalize_flux',
#         'pad_size',
#         'photon_threshold',
#         'photon_filter',
#         'preprocessing_binning',
#         'outofplane-angle',
#         'ref_axis_q',
#         'reload_previous',
#         'reload_orthogonal',
#         'rocking-angle',
#         'rocking-angle',
#         'sample-detector-distance',
#         'save-dir',
#         'save_rawdata',
#         'save_as_int',
#         'save_to_mat',
#         'save_to_npz',
#         'save_to_vti',
#         'specfile-path',
#         'use_rawdata',
#         'voxel-size'
#     ],
#     'pynx': [
#         'save_dir',
#         'data',
#         'mask',
#         'data2cxi',
#         'auto_center_resize',
#         'support_type',
#         'support_type',
#         'support',
#         'support_threshold',
#         'support_threshold_method',
#         'support_only_shrink',
#         'support_update_period',
#         'support_smooth_width_begin',
#         'support_smooth_width_end',
#         'support_post_expand',
#         'psf',
#         'nb_raar',
#         'nb_hio',
#         'nb_er',
#         'nb_ml',
#         'nb_run',
#         'nb_run_keep',
#         'zero_mask',
#         'crop_output',
#         'positivity',
#         'beta',
#         'detwin',
#         'rebin',
#         'detector_distance',
#         'pixel_size_detector',
#         'wavelength',
#         'verbose',
#         'output_format',
#         'live_plot',
#         'save_plot',
#         'mpi'
#     ]
# }
