# AUTHORIZED_KEYS = [
#     "metadata",
#     "preprocessing_output_shape",
#     "energy",
#     "roi",
#     "hkl",
#     "det_reference_voxel_method",
#     "det_reference_voxel",
#     "q_lab_reference",
#     "q_lab_max",
#     "q_lab_com",
#     "det_calib_parameters",
#     "voxel_size",
#     "apodize",
#     "flip",
#     "isosurface",
#     "show",
#     "verbose",
#     "data",
#     "mask",
#     "data2cxi",
#     "auto_center_resize",
#     "support_type",
#     "support_size",
#     "support",
#     "support_threshold",
#     "support_threshold_method",
#     "support_only_shrink",
#     "support_update_period",
#     "support_smooth_width_begin",
#     "support_smooth_width_end",
#     "support_post_expand",
#     "psf",
#     "nb_raar",
#     "nb_hio",
#     "nb_er",
#     "nb_ml",
#     "nb_run",
#     "nb_run_keep",
#     "zero_mask",
#     "crop_output",
#     "positivity",
#     "beta",
#     "detwin",
#     "rebin",
#     "detector_distance",
#     "pixel_size_detector",
#     "wavelength",
#     "verbose",
#     "output_format",
#     "live_plot",
#     "save_plot",
#     "mpi"
# ]

AUTHORIZED_KEYS = {
    "cdiutils": [
        "metadata",
        "preprocessing_output_shape",
        "energy",
        "roi",
        "hkl",
        "det_reference_voxel_method",
        "det_reference_voxel",
        "q_lab_reference",
        "q_lab_max",
        "q_lab_com",
        "det_calib_parameters",
        "voxel_size",
        "apodize",
        "flip",
        "isosurface",
        "show",
        "verbose"
    ],
    "pynx": [
        "data",
        "mask",
        "data2cxi",
        "auto_center_resize",
        "support_type",
        "support_size",
        "support",
        "support_threshold",
        "support_threshold_method",
        "support_only_shrink",
        "support_update_period",
        "support_smooth_width_begin",
        "support_smooth_width_end",
        "support_post_expand",
        "psf",
        "nb_raar",
        "nb_hio",
        "nb_er",
        "nb_ml",
        "nb_run",
        "nb_run_keep",
        "zero_mask",
        "crop_output",
        "positivity",
        "beta",
        "detwin",
        "rebin",
        "detector_distance",
        "pixel_size_detector",
        "wavelength",
        "verbose",
        "output_format",
        "live_plot",
        "save_plot",
        "mpi"
    ]
}