name: Mirror to GitLab

on:
  push:
    branches:
      - dev
      - master
    workflow_dispatch:  # manuel trigger
      inputs:
        force_push:
          description: 'Force push to GitLab'
          required: false
          default: 'true'
          type: choice
          options:
            - 'true'
            - 'false'
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for proper mirroring
      
      - name: Mirror to ESRF GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_MIRROR_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.esrf.fr/ada/cdiutils.git
          if [ "${{ inputs.force_push }}" == "true" ]; then
            git push gitlab ${GITHUB_REF#refs/heads/} --force
          else
            git push gitlab ${GITHUB_REF#refs/heads/}
          fi
